import { Open_Sans } from "next/font/google";
import type { Metadata } from "next";
import Menu from "@/components/Sidebar/Menu";
import "./global.css"

const open_sans = Open_Sans({ weight: "700", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body suppressHydrationWarning={true} className={open_sans.className}>
          <div className="flex">
            <Menu />
            {children}
          </div>
        </body>
      </html>
  );
}
